# Generated by Django 3.1.2 on 2020-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20201009_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='artist',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(),
        ),
    ]
